# Generated by Django 2.2.24 on 2025-04-07 06:50

from django.db import migrations


def find_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year >= 2015:
            Flat.objects.filter(pk=flat.pk).update(new_building=True)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(find_new_building),
    ]
