# Generated by Django 2.2.24 on 2025-04-08 10:48
import phonenumbers

from django.db import migrations


def add_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(phonenumber):
            Flat.objects.filter(pk=flat.pk).update(
                owner_pure_phone=phonenumbers.format_number(phonenumber, phonenumbers.PhoneNumberFormat.E164))
        else:
            Flat.objects.filter(pk=flat.pk).update(owner_pure_phone='Некорректный номер телефона')


def cler_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        Flat.objects.filter(pk=flat.pk).update(owner_pure_phone='')


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20250408_1232'),
    ]

    operations = [
        migrations.RunPython(add_owner_pure_phone, cler_owner_pure_phone),
    ]
