# Generated by Django 2.2.24 on 2025-04-14 07:14

from django.db import migrations


def copy_data_to_owner(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20250414_1012'),
    ]

    operations = [
        migrations.RunPython(copy_data_to_owner)
    ]
