# Generated by Django 2.2.24 on 2025-04-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20250415_1049'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together=set(),
        ),
    ]
