# Generated by Django 2.2.24 on 2025-04-15 13:00

from django.db import migrations
from django.db import transaction


@transaction.atomic
def copy_flat_to_owner(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for owner in Owner.objects.all().iterator():
        flat = Flat.objects.filter(owner=owner.owner, owners_phonenumber=owner.owners_phonenumber)
        owner.flat_in_ownership.set(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20250415_1559'),
    ]

    operations = [
        migrations.RunPython(copy_flat_to_owner)
    ]
