# Generated by Django 2.2.24 on 2025-04-17 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20250417_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='property.Flat', verbose_name='Квартира, на которую пожаловались'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complainer', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался'),
        ),
    ]
