# Generated by Django 2.2.24 on 2025-04-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_auto_20250419_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='flat_in_ownership',
        ),
        migrations.AddField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='owners', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
